name: 'YAML schema validation'
description: 'YAML schema validation using https://github.com/23andMe/Yamale'
author: gregor
branding:
  icon: 'file-text'
  color: 'blue'
inputs:
  dir:
    description: 'Content directory'
    required: true
  strict:
    description: 'Enable strict mode. Set to a non-empty string to enable.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
