name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: test-job
    steps:
      - uses: actions/checkout@v2
      - name: Validate
        uses: gregor-grote/yaml-schema-validator-github-action@master
        with:
          dir: data
